<?php
/**
 * Automatically generated by the Keyring.class.php ->update() method, using offical grooveshark libraries
 * controllerKey must be manually updated, as it requires decompilation of a .swf. See the /documentation/SecureKeys.txt file for more information
 * Autogenerated at 01 January 2015 22:52:09 
 */ 
	$keyCache = array(
		'clientRevision' => 20130520,
		'revToken' => 'nuggetsOfBaller',
		'clientLibrary' => 'htmlshark',
		'controllerKey' => 'chickenFingers',
	);